services:
  web:
    build: .

    container_name: marketplace-analytics-fastapi

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db
      - redis

    restart: always

  celery:
    build: .

    container_name: marketplace-analytics-celery

    env_file:
      - .env

    depends_on:
      - redis
      - db
    
    command: uv run celery -A src.marketplace_analytics_service.core.celery_app:celery_app worker --loglevel=info
  db:
    image: postgres:17-alpine

    container_name: marketplace-analytics-postgres

    ports:
      - "5432:5432"

    env_file:
      - .env

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

    container_name: marketplace-analytics-redis

    ports:
      - "6379:6379"

    env_file:
      - .env

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    volumes:
      - redis_data:/data

    

volumes:
  postgres_data:
  redis_data:
